-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, A.LENGTH
FROM (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS A, FISH_INFO I, FISH_NAME_INFO N
WHERE A.FISH_TYPE=I.FISH_TYPE
AND A.LENGTH=I.LENGTH
AND A.FISH_TYPE = N.FISH_TYPE
ORDER BY I.ID