-- 코드를 입력하세요
SELECT C.CAR_ID, ROUND(AVG(C.DURATION)+1, 1) AS AVERAGE_DURATION
FROM (
    SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) AS C
GROUP BY C.CAR_ID
HAVING ROUND(AVG(C.DURATION), 1) > 6
ORDER BY AVERAGE_DURATION DESC, C.CAR_ID DESC


-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE))+1, 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION > 6
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC