-- 코드를 입력하세요
SELECT I. REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    ROUND(AVG(I.REVIEW_SCORE),2) AS SCORE
FROM (
    SELECT R.REST_ID,
        REST_NAME,
        FOOD_TYPE,
        FAVORITES,
        ADDRESS,
        REVIEW_SCORE
    FROM REST_INFO AS I, 
        REST_REVIEW AS R
    WHERE I.REST_ID=R.REST_ID
    AND I.ADDRESS LIKE '서울%'
    ) AS I
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC