SELECT M.MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
GROUP BY R.MEMBER_ID
ORDER BY COUNT(REVIEW_TEXT) DESC, REVIEW_DATE ASC, REVIEW_TEXT ASC