SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C,
(
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE LIKE '2022-08%'
    OR START_DATE LIKE '2022-09%'
    OR START_DATE LIKE '2022-10%'
    GROUP BY CAR_ID
    HAVING COUNT(*) > 4
) AS I
WHERE C.CAR_ID = I.CAR_ID
AND C.START_DATE>="2022-08-01" 
AND C.START_DATE<"2022-11-01"
GROUP BY MONTH, C.CAR_ID
ORDER BY MONTH, C.CAR_ID DESC

-- main 쿼리에 날짜를 안 붙임;;;;