-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(END_DATE) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE LIKE '2022%'
AND MONTH(START_DATE) BETWEEN '08' AND '11'
GROUP BY CAR_ID HAVING COUNT(*) > 4
ORDER BY MONTH, CAR_ID DESC

-- 코드를 입력하세요
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE LIKE '2022%'
AND MONTH(START_DATE) BETWEEN '08' AND '11'
GROUP BY CAR_ID HAVING COUNT(*) > 4

SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C,
(SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE LIKE '2022%'
    AND MONTH(START_DATE) BETWEEN '08' AND '11'
    GROUP BY CAR_ID HAVING COUNT(*) > 4) AS I
WHERE C.CAR_ID = I.CAR_ID