-- 코드를 작성해주세요
SELECT COUNT(A.ID) AS FISH_COUNT, A.FISH_NAME
FROM (
    SELECT I.ID, N.FISH_TYPE, N.FISH_NAME
    FROM FISH_NAME_INFO N, FISH_INFO I
    WHERE N.FISH_TYPE =I.FISH_TYPE
) AS A
GROUP BY A.FISH_NAME
ORDER BY FISH_COUNT DESC