-- 코드를 작성해주세요
SELECT D.DEPT_ID, D.DEPT_NAME_EN, S.AVG_SAL
FROM HR_DEPARTMENT D, 
    (
        SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
        FROM HR_EMPLOYEES
        GROUP BY DEPT_ID
    ) AS S
WHERE D.DEPT_ID = S.DEPT_ID
ORDER BY S.AVG_SAL DESC