-- 코드를 입력하세요
SELECT M.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) AS M,
    FOOD_PRODUCT F
WHERE M.MAX_PRICE = F.PRICE
AND M.CATEGORY = F.CATEGORY
ORDER BY MAX_PRICE DESC