-- 코드를 작성해주세요
SELECT U.ITEM_ID AS ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I, (
    SELECT T.ITEM_ID AS ITEM_ID
    FROM ITEM_INFO I, ITEM_TREE T
    WHERE I.RARITY LIKE 'RARE'
    AND T.PARENT_ITEM_ID=I.ITEM_ID) AS U
WHERE I.ITEM_ID = U.ITEM_ID
ORDER BY U.ITEM_ID DESC