-- 코드를 입력하세요
SELECT T.AUTHOR_ID, T.AUTHOR_NAME, T.CATEGORY, SUM(T.TOTAL_SALES) AS TOTAL_SALES
FROM 
    (
        SELECT B.AUTHOR_ID, 
            A.AUTHOR_NAME, 
            B.CATEGORY, 
            B.PRICE*BS.SALES AS TOTAL_SALES
        FROM BOOK AS B, 
            AUTHOR AS A, 
            BOOK_SALES AS BS
        WHERE BS.SALES_DATE LIKE '2022-01%'
        AND BS.BOOK_ID = B.BOOK_ID
        AND A.AUTHOR_ID = B.AUTHOR_ID
    ) AS T
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY T.AUTHOR_ID ASC, T.CATEGORY DESC