-- 코드를 입력하세요
SELECT P.ID, P.NAME, H.HEAVY_USER
FROM PLACES P, 
    (
        SELECT CASE WHEN COUNT(HOST_ID)>1 THEN HOST_ID END AS HEAVY_USER
        FROM PLACES 
        GROUP BY HOST_ID
    ) AS H
WHERE P.HOST_ID=H.HEAVY_USER
ORDER BY ID